# Generated by Django 4.0.2 on 2022-02-15 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Answer option')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='body',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='response',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'text'), ('single', 'Select single'), ('multiple', 'Select multiple')], default='text', max_length=200, verbose_name='Question type'),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='multiple_choice',
            field=models.ManyToManyField(null=True, to='surveys.Choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='single_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_single_choice', to='surveys.choice'),
        ),
    ]
