# Generated by Django 4.0.2 on 2022-02-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_survey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='multiple_choice',
            field=models.ManyToManyField(to='surveys.Choice'),
        ),
    ]
